title: "Tyler Akana"
description: "Mechanical Engineering Portfolio | Projects and Experience"
theme: jekyll-theme-minimal
show_downloads: false
logo: /assets/img/mechanical_engineer_headshot.png  # Optional Logo
github:
  is_project_page: true
