title: "Tyler's Portfolio"
description: "Mechanical Engineering Portfolio | Projects and Experience"
theme: jekyll-theme-minimal
show_downloads: false
#logo: /assets/images/logo.png  # Optional Logo
github:
  is_project_page: true
